import AppKit
import Foundation

/// Clipboard history: text and images under ~/Library/Application Support/Pulse/clipboard.
/// Off until switched on in the hub. Keeps at most 500 items or 200 MB. Copies
/// that their source marks as concealed or transient are never stored.
@MainActor
final class LauncherClipboard {
    enum Kind: String, Codable {
        case text, png, tiff
    }

    struct Entry: Codable, Identifiable, Equatable {
        let id: String
        let kind: Kind
        let createdAt: Date
        let size: Int
        let digest: String
        /// Text only: the first 2000 characters, used for search and rows.
        let preview: String

        var fileName: String {
            switch kind {
            case .text: return id + ".txt"
            case .png: return id + ".png"
            case .tiff: return id + ".tiff"
            }
        }

        var firstLine: String {
            let line = preview.split(whereSeparator: { $0.isNewline }).first.map(String.init) ?? ""
            return String(line.trimmingCharacters(in: .whitespaces).prefix(120))
        }
    }

    static let maxItems = 500
    static let maxBytes = 200 * 1024 * 1024
    private static let maxCaptureBytes = 20 * 1024 * 1024
    private static let maxTextBytes = 1024 * 1024
    private static let hiddenTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private(set) var entries: [Entry] = []
    private var loaded = false
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// Watching starts and stops with this flag. Nothing is read while it is off.
    var enabled = false {
        didSet {
            guard enabled != oldValue else { return }
            if enabled { start() } else { stop() }
        }
    }

    private static var indexURL: URL {
        LauncherStorage.clipboardDirectory.appendingPathComponent("index.json")
    }

    private func fileURL(_ entry: Entry) -> URL {
        LauncherStorage.clipboardDirectory.appendingPathComponent(entry.fileName)
    }

    // MARK: - Watching

    private func start() {
        loadIfNeeded()
        lastChangeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.7, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    private func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let types = Set((pasteboard.types ?? []).map { $0.rawValue })
        guard types.isDisjoint(with: Self.hiddenTypes) else { return }
        if let text = pasteboard.string(forType: .string) {
            capture(text: text)
        } else if let png = pasteboard.data(forType: .png) {
            capture(image: png, kind: .png)
        } else if let tiff = pasteboard.data(forType: .tiff) {
            capture(image: tiff, kind: .tiff)
        }
    }

    /// Call after Pulse writes the pasteboard itself, so its own copy is not
    /// stored as new history.
    func noteOwnWrite() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    // MARK: - Capture

    private func capture(text: String) {
        loadIfNeeded()
        let data = Data(text.utf8)
        guard !text.isEmpty, data.count <= Self.maxTextBytes else { return }
        store(Entry(id: UUID().uuidString, kind: .text, createdAt: Date(), size: data.count,
                    digest: Self.digest(data), preview: String(text.prefix(2000))),
              data: data)
    }

    private func capture(image data: Data, kind: Kind) {
        loadIfNeeded()
        guard !data.isEmpty, data.count <= Self.maxCaptureBytes else { return }
        store(Entry(id: UUID().uuidString, kind: kind, createdAt: Date(), size: data.count,
                    digest: Self.digest(data), preview: ""),
              data: data)
    }

    private func store(_ entry: Entry, data: Data) {
        // The same copy again moves to the top instead of being stored twice.
        if let old = entries.firstIndex(where: { $0.digest == entry.digest && $0.kind == entry.kind }) {
            removeFile(entries[old])
            entries.remove(at: old)
        }
        LauncherStorage.ensure(LauncherStorage.clipboardDirectory)
        do {
            try data.write(to: fileURL(entry), options: .atomic)
        } catch {
            return
        }
        entries.insert(entry, at: 0)
        trim()
        saveIndex()
    }

    private func trim() {
        var total = entries.reduce(0) { $0 + $1.size }
        while entries.count > Self.maxItems || total > Self.maxBytes {
            guard let last = entries.popLast() else { break }
            total -= last.size
            removeFile(last)
        }
    }

    // MARK: - Reading and using

    /// Text entries containing the query, newest first. An empty query gives the newest.
    func matching(_ query: String, limit: Int) -> [Entry] {
        loadIfNeeded()
        let needle = query.trimmingCharacters(in: .whitespaces)
        guard !needle.isEmpty else { return Array(entries.prefix(limit)) }
        let found = entries.filter { $0.kind == .text && $0.preview.localizedCaseInsensitiveContains(needle) }
        return Array(found.prefix(limit))
    }

    func thumbnail(_ entry: Entry) -> NSImage? {
        NSImage(contentsOf: fileURL(entry))
    }

    /// Puts the stored copy back on the pasteboard.
    func copy(_ entry: Entry) {
        let pasteboard = NSPasteboard.general
        let url = fileURL(entry)
        pasteboard.clearContents()
        switch entry.kind {
        case .text:
            if let text = try? String(contentsOf: url, encoding: .utf8) {
                pasteboard.setString(text, forType: .string)
            }
        case .png:
            if let data = try? Data(contentsOf: url) { pasteboard.setData(data, forType: .png) }
        case .tiff:
            if let data = try? Data(contentsOf: url) { pasteboard.setData(data, forType: .tiff) }
        }
        noteOwnWrite()
    }

    func clear() {
        loadIfNeeded()
        for entry in entries { removeFile(entry) }
        entries = []
        saveIndex()
    }

    // MARK: - Disk

    private func loadIfNeeded() {
        guard !loaded else { return }
        loaded = true
        guard let data = try? Data(contentsOf: Self.indexURL),
              let saved = try? JSONDecoder().decode([Entry].self, from: data) else { return }
        // Drop index rows whose file has gone missing.
        entries = saved.filter {
            FileManager.default.fileExists(atPath: LauncherStorage.clipboardDirectory
                .appendingPathComponent($0.fileName).path)
        }
    }

    private func saveIndex() {
        LauncherStorage.ensure(LauncherStorage.clipboardDirectory)
        guard let data = try? JSONEncoder().encode(entries) else { return }
        try? data.write(to: Self.indexURL, options: .atomic)
    }

    private func removeFile(_ entry: Entry) {
        try? FileManager.default.removeItem(at: fileURL(entry))
    }

    /// FNV-1a over the bytes: stable across launches, unlike `hashValue`.
    private static func digest(_ data: Data) -> String {
        var hash: UInt64 = 0xcbf2_9ce4_8422_2325
        for byte in data {
            hash = (hash ^ UInt64(byte)) &* 0x0000_0100_0000_01b3
        }
        return String(hash, radix: 16)
    }
}
